name: CI

on: [pull_request, push]

jobs:
  test:
    strategy:
      matrix:
        node-version: ['14', '16', '18']
    runs-on: ubuntu-latest

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn

      - run: yarn format

      - run: yarn run tsc

      - run: yarn build
