name: TypeScript CI

on: [pull_request, push]

jobs:
  test:
    strategy:
      matrix:
        node: ['16', '18']
    runs-on: ubuntu-latest

    name: Test ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
          cache: 'yarn'

      - run: yarn

      - run: yarn format

      - run: yarn run tsc

      - run: yarn build
